<?php
$siteID = Mage::getStoreConfig('rekko_section/rekko_group/site_ID');
if ($siteID):
    $_product = Mage::registry('current_product');
    $catIds = $_product->getCategoryIds();
    $category = array();
    foreach ($catIds AS $cid) {
        $category[] = Mage::getModel('catalog/category')->load($cid)->getName();
    }
    $catNames = implode(',', $category);
    ?>
    <script type="text/javascript">
        window.convert_productCode = "<?php echo $_product->getSku(); ?>";
        window.convert_productCategory = "<?php echo $catNames; ?>";
    </script>
<?php endif; ?>
