<?php
$moduleName = 'Smashmetrics_Rekko'; //eg Mage_Cms
$merchantID = Mage::getStoreConfig('rekko_section/rekko_group/merchant_ID');
$enabled = Mage::getStoreConfig('advanced/modules_disable_output/' . $moduleName);
?>

<?php if ($enabled == 0): ?>
    <!--Script tag for setup.js-->
    <script type="text/javascript">
        var cvtJsHost = (("https:" == document.location.protocol)
            ? "https://dnhgz729v27ca.cloudfront.net/" : "http://use.convertglobal.com/");
        document.write(unescape("%3Cscript src='" + cvtJsHost
                                    + "client/staging_setup.js' type='text/javascript'%3E%3C/script%3E"));
    </script>
    <?php $cartItems = $this->getCartItems(); ?>
    <?php if (count($cartItems) > 0): ?>
        <script type="text/javascript">
            if (!window.convert_cart) {
                window.convert_cart = {};
                convert_cart.shoppingCartItems = new Array();
            }
            <?php foreach ($products as $items) { ?>
            var convert_item = {};
            convert_item.sku = "<?php echo $items['sku']; ?>";
            convert_item.category = "<?php echo $items['category']; ?>";
            convert_item.quantity =<?php echo $items['qty']; ?>;
            convert_item.price =<?php echo $items['price']; ?>;
            convert_cart.shoppingCartItems.push(convert_item);
            <?php } ?>
        </script>
    <?php endif; ?>
    <!--End Tagging Your Cart for Items-->

    <?php $orderdetails = $this->getOrderDetails(); ?>

    <?php // if this quote_id is successpage  then there was a transaction. ?>
    <?php if ($orderdetails['quote_id'] == 'successpage'): ?>
        <script type="text/javascript">
            convert_cart.isPurchased = true;
        </script>
    <?php endif; ?>

    <?php if ($orderdetails['quote_id'] > 0 or $orderdetails['quote_id'] == 'successpage'): ?>
        <?php //order tagging code //?>
        <script type="text/javascript">
            if (!window.convert_cart) {
                window.convert_cart = {};
                convert_cart.shoppingCartItems = new Array();
            }
            convert_cart.totalCost =<?php echo $orderdetails['grand_total']; ?>;
            <?php if ($orderdetails['tax'] != ''): ?>
            convert_cart.taxes =<?php echo $orderdetails['tax']; ?>;
            <?php endif; ?>
            convert_cart.discount =<?php echo $orderdetails['discount']; ?>;
            <?php if ($orderdetails['shipping_total'] != ''): ?>
            convert_cart.shipping =<?php echo $orderdetails['shipping_total']; ?>;
            <?php endif; ?>
            <?php if ($orderdetails['coupon_code'] != ''): ?>
            convert_cart.promoCode = "<?php echo $orderdetails['coupon_code']; ?>";
            <?php endif; ?>
            <?php if ($orderdetails['orderid'] != ''): ?>
            convert_cart.orderId = "<?php echo $orderdetails['orderid']; ?>";
            <?php endif; ?>
        </script>
        <!--order tagging code-->
    <?php endif; ?>

    <?php //Visitor Profile Tagging ?>

    <?php $customerDet = $this->getCustomerDetails(); ?>

    <? if ($customerDet):?>
        <script type="text/javascript">
            if (!window.convert_profile) {
                window.convert_profile = {};
            }
            convert_profile.firstName = "<?php echo $customerDet['firstname']; ?>";
            convert_profile.lastName = "<?php echo $customerDet['lastname']; ?>";
            convert_profile.email = "<?php echo $customerDet['email']; ?>";
        </script>
        <!--End Visitor Profile Tagging-->
    <?php endif; ?>
    <script type="text/javascript">
        window.convert = new Convert("<?php echo $merchantID; ?>");
        convert.init();
    </script>
<?php endif; ?>
