<?php
//
//$num_unopt = Mage::getModel('gtspeed/image')->getCollection()->addOptimizedFilter(0)->getSize();
//
//$min_css = Mage::getStoreConfigFlag('gtspeed/cssjs/min_css');
//$min_js = Mage::getStoreConfigFlag('gtspeed/cssjs/min_js');
//$merge_css = Mage::getStoreConfigFlag('gtspeed/cssjs/merge_css');
//$merge_js = Mage::getStoreConfigFlag('gtspeed/cssjs/merge_js');

?>
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Smashmetrics Rekko'); ?></h3></td>
        </tr>
    </table>
</div>
<table class="gtspeed" width="100%" cellspacing="25">
    <tbody>
        <tr>
           

            <td class="gtspeed_r"> 
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <h4>About Smashmetrics Rekko</h4>
                    </div>
                       <fieldset>
                        <table class="form-list" cellspacing="6">
                            <tr>
                                <td class="gt-logo"><img src="<?php echo $this->getSkinUrl('rekko/images/logo.png'); ?>"/></td>
                                <td><a href="http://smashmetrics.com/" target="_blank">Smashmetrics</a>.<br/>
                                    
                                    SmashMetrics is a digital marketing firm helping businesses (like yours) sell more products and services online. Our partners & employees have experience leading marketing campaigns and merchandising for companies like Walmart, Sam’s Club, Zappos, P&G and other Fortune 500 companies.
Our customers benefit from our drive to:
<ul class="rekkoDetails">
    <li> Create more profitable sales & revenue</li>
    <li>Engage in site testing for improved visitor to sale ratios</li>
    <li>Refine ecommerce merchandising strategies</li>
    <li>Construct and maintain a remarketing program to improve conversions</li>
</ul>                                   
</td>
                            </tr>
                        </table>
                    </fieldset>
                </div>
        
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <h4>Troubleshooting</h4>
                    </div>
                    <fieldset>
                        
                        <div class="troubleShootContents">
                        <span class="smashheading">What is Rekko? </span><br/>
                        Rekko is a the ultimate onsite marketing tool. It uses their sophisticated software platform in the cloud to deliver behavioral targeted campaigns to your site visitors based on their actions, page views, transactions, locations, and devices. From improving abandoned carts to increasing conversions Rekko helps you get more sales from your current customers.
I'm having installation problems. 
                        </div>
<div class="troubleShootContents">
<span class="smashheading">Can you help me?</span><br/>
SmashMetrics knows that some times you need help or support. If you would like us to have our professionals help you with your installation of Rekko or need Rekko support let us know at <a href="mailto:info@smashmetrics.com">info@smashmetrics.com</a>
</div>
<div class="troubleShootContents">
<span class="smashheading">How do I set up "inline content" on Magento?</span><br/>
Inline content is set up by creating an HTML container called a DIV and then assigning the DIV a unique ID. If this sounds too complicated for you and you would like help with your Magento installation - please contact us for more support.
</div>
<div class="troubleShootContents">
<span class="smashheading">What installation of Rekko is being installed?</span><br/>
Rekko has 2 types of installation. The "Simple" install is only the basic features of Rekko and only requires a simple javascript addition to your website's <head> area. SmashMetrics built this Magento extension specifically to install the much more complicated and feature-rich "Advanced" or "Full" version. Using this extension gives you all of the advanced features available in Rekko's advanced system.
</div>               
                        
                     </fieldset>
                </div>
            </td>
        </tr>
    </tbody>
</table>
<script>



</script>
