<style type="text/css">

  #rekko_signup {
  margin-top:10px;
  margin-bottom: 30px;
  }

  #rekko_signup .getrekko-button {
  background-color: #72ce3f;
  background: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0%, #72ce3f), color-stop(100%, #62bc30));
  background: -webkit-linear-gradient(top, #72ce3f, #62bc30);
  background: -moz-linear-gradient(top, #72ce3f, #62bc30);
  background: -o-linear-gradient(top, #72ce3f, #62bc30);
  background: linear-gradient(top, #72ce3f, #62bc30);
  border: 1px solid #40B200 !important;
  font-size: 18px;
  font-family:Roboto, 'Helvetica Neue', 'HelveticaNeue-Light', 'Helvetica Neue Light', Helvetica, Arial, 'Lucida Grande', sans-serif !important;
  color: white;
  text-decoration: none;
  text-align: center;
  vertical-align: middle;
  letter-spacing: -.1px;
  -webkit-transition-property: all;
  -moz-transition-property: all;
  -o-transition-property: all;
  transition-property: all;
  -webkit-transition-duration: 0.3s;
  -moz-transition-duration: 0.3s;
  -o-transition-duration: 0.3s;
  transition-duration: 0.3s;
  -webkit-box-shadow: inset 0px 1px 0px rgba(255, 255, 255, 0.3), inset 0px -1px 1px rgba(255, 255, 255, 0.15), 0px 7px 0px #48A116, 0px 8px 3px rgba(0, 0, 0, 0.3);
  -moz-box-shadow: inset 0px 1px 0px rgba(255, 255, 255, 0.3), inset 0px -1px 1px rgba(255, 255, 255, 0.15), 0px 7px 0px #48A116, 0px 8px 3px rgba(0, 0, 0, 0.3);
  box-shadow: inset 0px 1px 0px rgba(255, 255, 255, 0.3), inset 0px -1px 1px rgba(255, 255, 255, 0.15), 0px 7px 0px #48A116, 0px 8px 3px rgba(0, 0, 0, 0.3);
  text-shadow: none;
  display: block;
  position: relative;
  top: 0px;
  margin: 0;
  width: 350px;
  height: 32px;
  padding: 0px;
  white-space: normal;
  zoom: 1;
  cursor: pointer;
  border-radius: 3px 2px;
  }


</style>


<table width="750px" cellpadding="10px">
  
  <tr>
    
    <td>
      
      <h1>About Rekko Personalization Plugin</h1>
      
      <p>Rekko is a complete Cloud Marketing Suite equipping small online businesses with the tools they need to drive more leads, conversions, revenue, customer lifetime value and reduce cart abandonments without additional work from your I.T. staff.</p>

      <p>This Plugin makes implementation and integration with the Rekko Cloud Marketing Suite quick and simple. In just a few minutes, you can be fully integrated with Rekko and take advantage of great features like Product Recommendations, Top Selling Products, Shopping Cart Recovery Emails, Onsite Campaign Testing, and much, much more.</p>
      
    </td>
    
  </tr>
  
  <tr>
    
    <td>
      
      <h2>What is Rekko?</h2>
      
      <p>Rekko is a complete Cloud Marketing Suite. It delivers behavioral targeted campaigns to your site visitors based on their actions, page views, transactions, locations, devices and more! From improving abandoned carts to increasing conversions, Rekko helps you get more conversions and leads from your visitors.</p>
      
      <h3>How can I get Rekko?</h3>
      
      <div id="rekko_signup">

	<button class="getrekko-button" onclick=window.open("http://rekko.com");>Click Here to Sign Up for Rekko</button>

      </div>

    </td>
    
  </tr>
  
  <tr>
    
    <td>
      
      <h2>What's my Site ID?</h2>
      
      <p>Your Site ID is how Rekko identifies your account. If you've signed up for Rekko through <a href="http://rekko.com">our website</a>, you should have received your Site ID in your welcome email. If you're unsure or still can't find it, you can find your Site ID by logging into the Rekko Dashboard and going into your Account Preferences. You can also just reach out to us. We're happy to help!</p>
      
      <h2>How do I add my Site ID to the Magento Plugin?</h2>
      
      <p>Under the System menu, click on Configurations. From the left side menu, select Settings under Rekko. You'll be able to input your Site ID here.</p>
      <a href="http://rekko-images.s3.amazonaws.com/magento_config.png" target="_blank"><img src="http://rekko-images.s3.amazonaws.com/magento_config.png" alt="Rekko Configuration Steps in Magento" style="width:750px;height:414px;margin:10px;"></a>
      <figcaption style="margin-bottom:10px;"><center>Click Image to Enlarge in New Tab</center></figcaption>
      
      <h2>I'm having installation issues, can you help me?</h2>
      
      <p>At Rekko, we know that sometimes you need help or support. If you would like us to have our professionals help you with your installation of Rekko or need Rekko support let us know! You can contact us at:</p>
      
      <p><a href="mailto:help@rekko.com" target="_top">Rekko Support Email</a></p>
      <p><a href="https://rekko.rhinosupport.com/helpdesk.htm">Rekko Ticketing</a></p>
      <p><a href="http://rekko.com/community/">Rekko Community Forums</a></p>
      
      <h2>How do I import my product feed into Rekko?</h2>
      
      <p>With your website's platform on Magento, exporting and importing your product feed is made easy. Choose and install from one of the many product import/export extensions from the <a href="http://www.magentocommerce.com/">Magento Commerce site</a> if you haven't already. The plugin should allow for you to export your feed in CSV format. </p>
      
      <p>Once installed, you should be able to export the fields listed below. As we mention below, the only field that is required is the product_id and each column should be labeled with our variable names in lower-case.</p>
      
      <h2>What format should my product feed be in for Rekko?</h2>
      
      <p>While headers are required in the file (lower-case), columns in the Product Feed do not need to follow a specific order. Please note that all fields are optional except for [product_id]. <b>The Product Feed must be in a proper CSV format – meaning, each row should have a field associated with the header even if it’s left blank; i.e. , , . </b></p>
      
      <p>The following header names should be at the top of each column, respectfully.</p>
      
      <ul>
	<li>
          <b>product_id:</b> Your product’s unique item number. This is case sensitive and is the only REQUIRED column and field for a product feed.</li>
	<li><b>product_name</b></li>
	<li><b>description</b></li>
	<li><b>product_category:</b> Multiple categories are accepted so long as they are delineated with a comma (,) and the field is surrounded by quotations (“); e.g. ID1, some name, “category1, category2, category3”, a description, USD.</li>
	<li><b>grid_image_link:</b> This should not be a relative URL.</li>
	<li><b>feature_image_link:</b> This can be the same as the URL for Thumbnail so long as it is not a relative URL. </li>
	<li><b>product_link</b></li>
	<li><b>price:</b> Do NOT include currency symbols; e.g. dollar signs ($). </li>
	<li><b>brand</b></li>
	<li><b>quantity:</b> Used for quantity of inventory (recommendations can be set to not display product if quantity is less than this value)</li>
	<li><b>rating:</b> Value lies between zero and five. Decimal values are supported.</li>
      </ul>
      
    </td>
    
  </tr>

</table>
