<table width="600px" cellpadding="10px">
	
	<tr>
	
		<td>
		
			<h1>About Rekko Personalization Plugin</h1>
		
			<p>Rekko is a complete Cloud Marketing Suite equipping small online businesses with the tools they need to drive more leads, conversions, revenue, customer lifetime value and reduce cart abandonments without additional work from your I.T. staff.</p>

			<p>This Plugin makes implementation and integration with the Rekko Cloud Marketing Suite quick and simple. In just a few minutes, you can be fully integrated with Rekko and take advantage of great features like Product Recommendations, Top Selling Products, Shopping Cart Recovery Emails, Onsite Campaign Testing, and much, much more.</p>
				
		</td>
		
	</tr>
	
	<tr>
	
		<td>
		
			<h2>What is Rekko?</h2>
		
			<p>Rekko is a complete Cloud Marketing Suite. It delivers behavioral targeted campaigns to your site visitors based on their actions, page views, transactions, locations, devices and more! From improving abandoned carts to increasing conversions, Rekko helps you get more conversions and leads from your visitors.</p>
			
			<h3>How can I get Rekko?</h3>
			
			<p>Simple! Just head over to the <a href="http://rekko.com">Rekko website</a> to get signed up.</p>

		</td>
		
	</tr>
	
	<tr>
	
		<td>
		
			<h1>Which installation of Rekko is this Plugin installing?</h1>
		
			<p>Rekko's Full Tagging Implementation is being installed. This means you'll be able to take full advantage of all of Rekko's extensive Profiling Engine as well as all of the content delivery features like Top Selling Products and Product Recommendations.</p>
			
			<h2>What's my Site ID?</h2>
			
			<p>Your Site ID is how Rekko identifies your account. If you've signed up for Rekko through <a href="http://rekko.com">our website</a>, you should have received your Site ID in your welcome email. If you're unsure or still can't find it, you can find your Site ID by logging into the Rekko Dashboard and going into your Account Preferences. You can also just reach out to us. We're happy to help!</p>
			
			<h2>How do I add my Site ID to the Magento Plugin?</h2>
			
			<p>Under the System menu, click on Configurations. From the left side menu, select Settings under Rekko. You'll be able to input your Site ID here.</p>
			
			<h2>I'm having installation issues, can you help me?</h2>
		
			<p>At Rekko, we know that sometimes you need help or support. If you would like us to have our professionals help you with your installation of Rekko or need Rekko support let us know! You can contact us at:</p>
			
			<p><a href="mailto:help@rekko.com" target="_top">Rekko Support Email</a></p>
			<p><a href="https://rekko.rhinosupport.com/helpdesk.htm">Rekko Ticketing</a></p>
			<p><a href="http://rekko.com/community/">Rekko Community Forums</a></p>
			
		</td>
		
	</tr>

</table>