<?php
$moduleName = 'Smashmetrics_Rekko'; //eg Mage_Cms
$merchantID = Mage::getStoreConfig('rekko_section/rekko_group/merchant_ID');
$domain_name = Mage::getStoreConfig('rekko_section/rekko_group/domain_name');
$enabled = Mage::getStoreConfig('advanced/modules_disable_output/' . $moduleName);
if ($enabled == 0):
    $_product = Mage::registry('current_product');
    $catIds = $_product->getCategoryIds();
    $category = array();
    foreach ($catIds AS $cid) {
        $category[] = Mage::getModel('catalog/category')->load($cid)->getName();
    }
    $catNames = implode(',', $category);
    ?>
    <!--Tagging Your Product Pages-->
    <script type="text/javascript">
        window.convert_productCode = "<?php echo $_product->getSku(); ?>";
        window.convert_productCategory = "<?php echo $catNames; ?>";
    </script>
    <!--End Tagging Your Product Pages-->
<?php endif; ?>